- job:
    name: ceph-pr-docs
    display-name: 'ceph: Pull Requests Docs Check'
    concurrent: true
    node: trusty && x86_64
    project-type: freestyle
    defaults: global
    quiet-period: 5
    block-downstream: false
    block-upstream: false
    properties:
      - github:
          url: https://github.com/ceph/ceph
      - build-discarder:
          days-to-keep: 14

    discard-old-builds: true

    triggers:
      - github-pull-request:
          allow-whitelist-orgs-as-admins: true
          org-list:
            - ceph
          cancel-builds-on-update: true
          only-trigger-phrase: false
          trigger-phrase: 'jenkins test docs.*'
          github-hooks: true
          permit-all: true
          auto-close-on-fail: false
          status-context: "Docs: build check"
          started-status: "Docs: building"
          success-status: "OK - docs built"
          failure-status: "Docs: failed with errors"

    scm:
      - git:
          url: https://github.com/ceph/ceph
          browser: auto
          branches:
            - ${sha1}
          refspec: +refs/pull/${ghprbPullId}/*:refs/remotes/origin/pr/${ghprbPullId}/*
          skip-tag: true
          timeout: 20
          wipe-workspace: true

    builders:
      - shell:
          !include-raw: ../../build/build
