- job:
    name: teuthology-pull-requests
    node: trusty && huge
    project-type: freestyle
    defaults: global
    concurrent: true
    display-name: 'Teuthology: Pull Requests'
    quiet-period: 5
    block-downstream: false
    block-upstream: false
    retry-count: 3
    properties:
      - build-discarder:
          days-to-keep: 15
          num-to-keep: 30
          artifact-days-to-keep: -1
          artifact-num-to-keep: -1
      - github:
          url: https://github.com/ceph/teuthology/

    parameters:
      - string:
          name: sha1
          description: "commit id or a refname, like 'origin/pr/72/head'"
      - string:
          name: ghprbPullId
          description: "A pull request ID, like '72' in https://github.com/ceph/ceph/pull/72"

    triggers:
      - github-pull-request:
          admin-list:
            - alfredodeza
            - ktdreyer
            - zmc
            - andrewschoen
            - dmick
            - gregsfortytwo
          org-list:
            - ceph
          white-list:
            - jcsp
            - GregMeno
            - dzafman
            - dillaman
            - dachary
            - liewegas
            - idryomov
            - vasukulkarni
            - ivotron
          trigger-phrase: 'jenkins test.*|jenkins retest.*'
          only-trigger-phrase: false
          github-hooks: true
          permit-all: false
          auto-close-on-fail: false

    scm:
      - git:
          url: https://github.com/ceph/teuthology.git
          branches:
            - ${sha1}
          refspec: +refs/pull/${ghprbPullId}/*:refs/remotes/origin/pr/${ghprbPullId}/*
          browser: auto
          timeout: 20
          skip-tag: true
          wipe-workspace: true

    builders:
      - shell:
          !include-raw:
            - ../../../scripts/build_utils.sh
            - ../../setup/setup
      - shell:
          !include-raw:
            - ../../../scripts/build_utils.sh
            - ../../build/build
