
- job:
    name: 'ceph-volume-scenario'
    node: vagrant&&libvirt&&(smithi||mira||dhc)
    concurrent: true
    defaults: global
    display-name: 'ceph-volume: individual scenario testing'
    quiet-period: 5
    block-downstream: false
    block-upstream: false
    retry-count: 3
    properties:
      - build-discarder:
          days-to-keep: 15
          artifact-days-to-keep: 15
      - github:
          url: https://github.com/ceph/ceph

    parameters:
      - string:
          name: SUBCOMMAND
          description: "The subcommand in ceph-volume we are testing. (lvm or simple)"
          default: "lvm"
      - string:
          name: SCENARIO
          description: "A full scenario name for ceph-volume testing, like xenial-bluestore-create"
      - string:
          name: CEPH_BRANCH
          description: "The ceph branch to test against"
          default: "master"
      - string:
          name: CEPH_SHA1
          description: "The ceph sha1 to test against"
          default: "latest"
      - string:
          name: CEPH_ANSIBLE_BRANCH
          description: "The ceph-ansible branch to test against"
          default: "master"
      - string:
          name: CEPH_REPO_URL
          description: "The full https url to clone from"
          default: "https://github.com/ceph/ceph.git"

    scm:
      - git:
          url: $CEPH_REPO_URL
          branches:
            - $CEPH_BRANCH
          refspec: +refs/pull/${ghprbPullId}/*:refs/remotes/origin/pr/${ghprbPullId}/*
          browser: auto
          timeout: 20
          skip-tag: true
          wipe-workspace: true

    builders:
      - shell:
          !include-raw:
            - ../../../scripts/build_utils.sh
            - ../../build/build

    publishers:
      - postbuildscript:
          builders:
            - role: SLAVE
              build-on:
                  - FAILURE
                  - ABORTED
              build-steps:
                - shell:
                    !include-raw:
                      - ../../../scripts/build_utils.sh
                      - ../../build/teardown

      - archive:
          artifacts: 'logs/**'
          allow-empty: true
          latest-only: false
