- scm:
    name: ceph-ansible
    scm:
      - git:
          url: https://github.com/ceph/ceph-ansible.git
          branches:
            - ${sha1}
          refspec: +refs/pull/${ghprbPullId}/*:refs/remotes/origin/pr/${ghprbPullId}/*
          browser: auto
          timeout: 20
          skip-tag: true
          wipe-workspace: false
          basedir: "ceph-ansible"

- job:
    name: ceph-ansible-pr-syntax-check
    node: ((centos7 || trusty) && x86_64) || (vagrant && libvirt && smithi)
    project-type: freestyle
    defaults: global
    concurrent: true
    display-name: 'ceph-ansible: Pull Requests Syntax Check'
    quiet-period: 5
    block-downstream: false
    block-upstream: false
    retry-count: 3
    properties:
      - build-discarder:
          days-to-keep: 15
          num-to-keep: 30
          artifact-days-to-keep: -1
          artifact-num-to-keep: -1
      - github:
          url: https://github.com/ceph/ceph-ansible

    parameters:
      - string:
          name: sha1
          description: "commit id or a refname, like 'origin/pr/72/head'"
      - string:
          name: ghprbPullId
          description: "A pull request ID, like '72' in https://github.com/ceph/ceph/pull/72"

    triggers:
      - github-pull-request:
          allow-whitelist-orgs-as-admins: true
          org-list:
            - ceph
          trigger-phrase: 'jenkins test playbook syntax'
          # This is set so the job can be manually triggered or by the ceph-ansible-pipeline multijob
          only-trigger-phrase: true
          github-hooks: true
          permit-all: true
          auto-close-on-fail: false
          status-context: "Testing: playbook syntax"
          started-status: "Running syntax checks on all playbooks"
          success-status: "OK - syntax checks completed"
          failure-status: "Syntax check failed with errors"

    scm:
      - ceph-ansible

    builders:
      - shell:
          !include-raw:
            - ../../../scripts/build_utils.sh
            - ../../build/build
