- scm:
    name: ceph-container
    scm:
      - git:
          url: https://github.com/ceph/ceph-container.git
          branches:
            - ${sha1}
          refspec: +refs/pull/${ghprbPullId}/*:refs/remotes/origin/pr/${ghprbPullId}/*
          browser: auto
          timeout: 20
          skip-tag: true
          wipe-workspace: false
          basedir: "ceph-container"

- job:
    name: ceph-container-flake8
    node: small && centos7
    defaults: global
    display-name: 'ceph-container-flake8'
    properties:
      - build-discarder:
          days-to-keep: 15
          num-to-keep: 30
          artifact-days-to-keep: -1
          artifact-num-to-keep: -1
      - github:
          url: https://github.com/ceph/ceph-container/

    parameters:
      - string:
          name: sha1
          description: "commit id or a refname, like 'origin/pr/72/head'"
      - string:
          name: ghprbPullId
          description: "A pull request ID, like '72' in https://github.com/ceph/ceph/pull/72"

    triggers:
      - github-pull-request:
          admin-list:
            - alfredodeza
            - ktdreyer
            - gmeno
            - zcerza
          org-list:
            - ceph
          trigger-phrase: 'jenkins flake8'
          only-trigger-phrase: false
          github-hooks: true
          permit-all: true
          auto-close-on-fail: false
          status-context: "Testing: for sloppy python"
          started-status: "Running: flake8"
          success-status: "OK - nice work"
          failure-status: "FAIL - please clean up for merge"

    scm:
      - ceph-container

    builders:
      - shell:
          !include-raw:
            - ../../build/build

