- job:
    name: ceph-pr-submodules
    node: centos || trusty
    project-type: freestyle
    defaults: global
    display-name: 'ceph: Pull Request modified submodules'
    concurrent: true
    quiet-period: 5
    block-downstream: false
    block-upstream: false
    retry-count: 3
    properties:
      - build-discarder:
          days-to-keep: 15
          artifact-days-to-keep: -1
          artifact-num-to-keep: -1
      - github:
          url: https://github.com/ceph/ceph/

    parameters:
      - string:
          name: sha1
          description: "commit id or a refname, like 'origin/pr/72/head'"
      - string:
          name: ghprbPullId
          description: "A pull request ID, like '72' in https://github.com/ceph/ceph/pull/72"

    triggers:
      - github-pull-request:
          allow-whitelist-orgs-as-admins: true
          org-list:
            - ceph
          trigger-phrase: 'jenkins test submodules'
          only-trigger-phrase: false
          github-hooks: true
          permit-all: true
          auto-close-on-fail: false
          status-context: "Unmodified Submodules"
          started-status: "checking if PR has modified submodules"
          success-status: "submodules for project are unmodified"
          failure-status: "Approval needed: modified submodules found"

    scm:
      - git:
          url: https://github.com/ceph/ceph.git
          branches:
            - ${sha1}
          refspec: +refs/pull/${ghprbPullId}/*:refs/remotes/origin/pr/${ghprbPullId}/*
          browser: auto
          timeout: 20
          skip-tag: true
          wipe-workspace: true

    builders:
      - shell:
          !include-raw:
            - ../../build/build
