
- job:
    name: 'ceph-ansible-scenario'
    node: vagrant&&libvirt
    concurrent: true
    defaults: global
    display-name: 'ceph-ansible: individual scenario testing'
    quiet-period: 5
    block-downstream: false
    block-upstream: false
    retry-count: 3
    properties:
      - build-discarder:
          days-to-keep: 15
          num-to-keep: 30
          artifact-days-to-keep: -1
          artifact-num-to-keep: -1
      - github:
          url: https://github.com/ceph/ceph-ansible

    parameters:
      - string:
          name: SCENARIO
          description: "A full scenario name for ceph-ansible testing, like jewel-ansible2.2-purge_cluster"
      - string:
          name: BRANCH
          description: "The ceph-ansible branch to test against"
          default: "master"
      - string:
          name: CEPH_DEV_BRANCH
          description: "The ceph dev branch to test against if using a dev-* scenario"
          default: "master"
      - string:
          name: CEPH_DEV_SHA1
          description: "The ceph sha1 to test against if using a dev-* scenario"
          default: "latest"
      - string:
          name: CEPH_DOCKER_REGISTRY
          description: "The docker registry used for containerized scenarios"
          default: "docker.io"
      - string:
          name: CEPH_DOCKER_IMAGE
          description: "The docker image used for containerized scenarios"
          default: "ceph/daemon"
      - string:
          name: CEPH_DOCKER_IMAGE_TAG
          description: "The docker image tag used for containerized scenarios"
          default: "latest"
      - string:
          name: RELEASE
          description: "The ceph release version used"
          default: "dev"
      - string:
          name: DEPLOYMENT
          description: "Type of deployment: container or non_container"
          default: "non_container"
      - string:
          name: DISTRIBUTION
          description: "The distribution used (ubuntu or centos)"
          default: "centos"

    scm:
      - git:
          url: https://github.com/ceph/ceph-ansible.git
          branches:
            - $BRANCH
          refspec: +refs/pull/${ghprbPullId}/*:refs/remotes/origin/pr/${ghprbPullId}/*
          browser: auto
          timeout: 20
          skip-tag: true
          wipe-workspace: true

    builders:
      - shell:
          !include-raw:
            - ../../../scripts/build_utils.sh
            - ../../build/build

    publishers:
      - postbuildscript:
          builders:
            - role: SLAVE
              build-on:
                  - FAILURE
                  - ABORTED
              build-steps:
                - shell:
                    !include-raw:
                      - ../../../scripts/build_utils.sh
                      - ../../build/teardown

      - archive:
          artifacts: 'logs/**'
          allow-empty: true
          latest-only: false
