- scm:
    name: ceph-medic
    scm:
      - git:
          url: https://github.com/ceph/ceph-medic
          branches:
            - ${sha1}
          refspec: +refs/pull/${ghprbPullId}/*:refs/remotes/origin/pr/${ghprbPullId}/*
          browser: auto
          timeout: 20
          basedir: "ceph-medic"
          skip-tag: true
          wipe-workspace: true


- job:
    name: ceph-medic-pull-requests
    description: Runs tox tests for ceph-medic on each GitHub PR
    project-type: freestyle
    node: python3 && centos7
    block-downstream: false
    block-upstream: false
    defaults: global
    display-name: 'ceph-medic: Pull Requests'
    quiet-period: 5
    retry-count: 3


    properties:
      - build-discarder:
          days-to-keep: 15
          num-to-keep: 30
          artifact-days-to-keep: 15
          artifact-num-to-keep: 15
      - github:
          url: https://github.com/ceph/ceph-medic/

    parameters:
      - string:
          name: sha1
          description: "commit id or a refname, like 'origin/pr/72/head'"
      - string:
          name: ghprbPullId
          description: "A pull request ID, like '72' in https://github.com/ceph/ceph/pull/72"

    triggers:
      - github-pull-request:
          admin-list:
            - alfredodeza
            - dmick
            - ktdreyer
            - andrewschoen
          org-list:
            - ceph
          only-trigger-phrase: false
          github-hooks: true
          permit-all: true
          auto-close-on-fail: false

    scm:
      - ceph-medic

    builders:
      - shell:
          !include-raw:
            - ../../../scripts/build_utils.sh
            - ../../build/build
