- scm:
    name: chacra
    scm:
      - git:
          url: https://github.com/ceph/chacra
          branches:
            - ${sha1}
          refspec: +refs/pull/${ghprbPullId}/*:refs/remotes/origin/pr/${ghprbPullId}/*
          browser: auto
          timeout: 20
          basedir: "chacra"
          skip-tag: true
          wipe-workspace: true

- scm:
    name: ceph-build
    scm:
      - git:
          url: https://github.com/ceph/ceph-build.git
          browser-url: https://github.com/ceph/ceph-build
          timeout: 20
          skip-tag: true
          wipe-workspace: false
          basedir: "ceph-build"
          branches:
            - origin/master


- job:
    name: chacra-pull-requests
    description: Runs tox tests for chacra on each GitHub PR
    project-type: freestyle
    node: trusty && small
    block-downstream: false
    block-upstream: false
    defaults: global
    display-name: 'chacra: Pull Requests'
    quiet-period: 5
    retry-count: 3


    properties:
      - build-discarder:
          days-to-keep: 15
          num-to-keep: 30
          artifact-days-to-keep: 15
          artifact-num-to-keep: 15
      - github:
          url: https://github.com/ceph/chacra/

    parameters:
      - string:
          name: sha1
          description: "commit id or a refname, like 'origin/pr/72/head'"
      - string:
          name: ghprbPullId
          description: "A pull request ID, like '72' in https://github.com/ceph/ceph/pull/72"

    triggers:
      - github-pull-request:
          admin-list:
            - alfredodeza
            - dmick
            - ktdreyer
            - andrewschoen
          org-list:
            - ceph
          only-trigger-phrase: false
          github-hooks: true
          permit-all: false
          auto-close-on-fail: false

    scm:
      - chacra
      - ceph-build

    builders:
      - shell:
          !include-raw:
            - ../../../scripts/build_utils.sh
            - ../../build/build
